In [30]:
# Dependencies
import requests
import pprint
import datetime
import pandas as pd
from config import xkey

url = "https://apidojo-yahoo-finance-v1.p.rapidapi.com/stock/v3/get-historical-data"
stocks = ['CVX', 'OXY', 'BP', 'XOM', 'EOG', 'TOT', 'DVN', 'RDS-B', 'EQNR', 'COP', 'CLR']
querystring = {"symbol": "CVX","region":"US"}
headers = {
    'x-rapidapi-key': xkey,
    'x-rapidapi-host': "apidojo-yahoo-finance-v1.p.rapidapi.com"
    }
response = requests.get(url, headers=headers, params=querystring).json()
pprint.pprint(response['prices'][0])

timestamp = datetime.datetime.fromtimestamp(response['prices'][0]['date'])
print(timestamp.strftime('%Y-%m-%d %H:%M:%S'))

{'adjclose': 103.58999633789062,
 'close': 103.58999633789062,
 'date': 1614805454,
 'high': 105.75,
 'low': 103.4000015258789,
 'open': 103.41000366210938,
 'volume': 14579557}
2021-03-03 15:04:14

In [27]:
stocks = ['CVX', 'OXY', 'BP', 'XOM', 'EOG', 'TOT', 'DVN', 'RDS-B', 'EQNR', 'COP', 'CLR']
date = []
openl = []
close = []
adjclose = []
high = []
low = []
ticker = []


for value in stocks:
    querystring = {"symbol":value,"region":"US"}
    response = requests.get(url, headers=headers, params=querystring).json()
    
    for i in range(len(response['prices'])):
        try:
            response['prices'][i]['volume']
        except KeyError:
            continue
        date.append(datetime.datetime.fromtimestamp(response['prices'][i]['date']).strftime('%Y-%m-%d %H:%M:%S'))
        openl.append(response['prices'][i]['open'])
        close.append(response['prices'][i]['close'])
        adjclose.append(response['prices'][i]['adjclose'])
        high.append(response['prices'][i]['high'])
        low.append(response['prices'][i]['low'])
        ticker.append(value)
        
print("complete")

complete

In [28]:
oil_df = pd.DataFrame({'ticker': ticker,
                       'date': date,
                       'open': openl,
                       'close': close,
                       'adjclose': adjclose,
                       'high': high,
                       'low': low,})
oil_df

,ticker,date,open,close,adjclose,high,low
0,CVX,2021-03-03 15:04:14,103.410004,103.589996,103.589996,105.750000,103.400002
1,CVX,2021-03-02 08:30:00,101.889999,102.440002,102.440002,103.309998,101.709999
2,CVX,2021-03-01 08:30:00,102.459999,102.050003,102.050003,103.800003,101.400002
3,CVX,2021-02-26 08:30:00,100.300003,100.000000,100.000000,101.059998,97.610001
4,CVX,2021-02-25 08:30:00,104.900002,102.349998,102.349998,104.959999,101.589996
...,...,...,...,...,...,...,...
2767,CLR,2020-03-10 08:30:00,8.800000,9.390000,9.390000,9.430000,7.060000
2768,CLR,2020-03-09 08:30:00,10.000000,7.050000,7.050000,10.150000,7.010000
2769,CLR,2020-03-06 08:30:00,16.680000,14.850000,14.850000,16.940001,14.670000
2770,CLR,2020-03-05 08:30:00,17.110001,17.490000,17.490000,17.680000,16.719999
2771,CLR,2020-03-04 08:30:00,18.010000,17.780001,17.780001,18.280001,17.110001

#####